"""
Medical Trend Analytics
Dedicated application for category-specific medical trend analysis.
"""
import streamlit as st
from datetime import datetime
import os
import sys
import markdown

# Local imports
from core.collector import PaperCollector
from core.trend_analyzer import TrendAnalyzer
from config.journals import get_journals_by_category

# ==========================================
# Helper Functions
# ==========================================
def get_secret(key, default=None):
    """Safely get secret from st.secrets or environment variables."""
    # First check env vars (good for dev/docker)
    val = os.environ.get(key)
    if val:
        return val
    # Then check st.secrets
    try:
        return st.secrets.get(key, default)
    except:
        return default

def clear_analysis_cache():
    """Clear all analysis results from session state."""
    keys_to_clear = [k for k in st.session_state.keys() if k.startswith("result_") or k.startswith("papers_")]
    for k in keys_to_clear:
        del st.session_state[k]

def generate_html_report(category: str, trend_analysis: str, papers: list) -> str:
    """Generate HTML report for download."""
    from datetime import datetime
    
    # Convert markdown to HTML
    trend_html = markdown.markdown(
        trend_analysis, 
        extensions=['tables', 'fenced_code', 'nl2br']
    ) if trend_analysis else ""
    
    # Build papers HTML
    papers_html = ""
    for i, p in enumerate(papers, 1):
        abstract = p.get('abstract', '')[:400]
        if len(p.get('abstract', '')) > 400:
            abstract += '...'
        papers_html += f'''
        <div class="paper">
            <div class="paper-title">{i}. <a href="{p['link']}" target="_blank">{p['title']}</a></div>
            <div class="paper-meta">📅 {p.get('published', 'Unknown')} | {p.get('source', '')}</div>
            <div class="paper-abstract">{abstract}</div>
        </div>'''
    
    html = f'''<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{category} Trend Report</title>
    <style>
        * {{ margin: 0; padding: 0; box-sizing: border-box; }}
        body {{ 
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
            line-height: 1.6; color: #333; max-width: 1200px; margin: 0 auto; padding: 20px; background: #f8f9fa;
        }}
        .header {{ 
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            color: white; padding: 30px; border-radius: 12px; margin-bottom: 30px; text-align: center;
        }}
        .header h1 {{ font-size: 2em; margin-bottom: 10px; }}
        .meta {{ color: rgba(255,255,255,0.9); font-size: 0.95em; }}
        .section {{ background: white; padding: 25px; margin-bottom: 20px; border-radius: 12px; box-shadow: 0 2px 10px rgba(0,0,0,0.08); }}
        .section h2 {{ color: #667eea; border-bottom: 2px solid #eee; padding-bottom: 10px; margin-bottom: 20px; }}
        .trend-analysis {{ background: #f0f4ff; padding: 20px; border-radius: 8px; border-left: 4px solid #667eea; }}
        .trend-analysis h3 {{ color: #4a5568; margin-top: 15px; margin-bottom: 8px; }}
        .trend-analysis table {{ width: 100%; border-collapse: collapse; margin: 15px 0; }}
        .trend-analysis th, .trend-analysis td {{ border: 1px solid #ddd; padding: 10px; text-align: left; }}
        .trend-analysis th {{ background: #667eea; color: white; }}
        .paper {{ border: 1px solid #e2e8f0; padding: 15px; margin-bottom: 12px; border-radius: 8px; }}
        .paper-title {{ font-weight: 600; color: #2d3748; margin-bottom: 8px; }}
        .paper-title a {{ color: #667eea; text-decoration: none; }}
        .paper-meta {{ color: #718096; font-size: 0.9em; margin-bottom: 10px; }}
        .paper-abstract {{ font-size: 0.95em; color: #4a5568; background: #f7fafc; padding: 12px; border-radius: 6px; }}
        .footer {{ text-align: center; color: #a0aec0; padding: 20px; font-size: 0.9em; }}
    </style>
</head>
<body>
    <div class="header">
        <h1>📊 {category} Trend Report</h1>
        <div class="meta">
            <p><strong>Generated:</strong> {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}</p>
            <p><strong>Papers Analyzed:</strong> {len(papers)}</p>
        </div>
    </div>
    <div class="section">
        <h2>🔬 AI Trend Analysis</h2>
        <div class="trend-analysis">{trend_html}</div>
    </div>
    <div class="section">
        <h2>📚 Source Papers ({len(papers)} total)</h2>
        {papers_html}
    </div>
    <div class="footer"><p>Generated by Medical Trend Analytics</p></div>
</body>
</html>'''
    return html

# ==========================================
# Main App
# ==========================================
def main():
    st.set_page_config(
        page_title="Medical Trend Analytics",
        page_icon="📈",
        layout="wide"
    )

    st.title("📈 Medical Trend Analytics")
    st.markdown("Category-specific insights from top medical journals.")

    # ------------------------------------------
    # Sidebar Configuration
    # ------------------------------------------
    with st.sidebar:
        st.header("⚙️ Settings")
        
        # Model
        default_model = get_secret("OLLAMA_MODEL", "gpt-oss:120b")
        model_name = st.text_input("Ollama Model", value=default_model)
        
        # Language Selection
        language = st.radio(
            "응답 언어 / Response Language",
            options=["en", "ko"],
            format_func=lambda x: "🇺🇸 English" if x == "en" else "🇰🇷 한국어",
            horizontal=True
        )
        
        # Time Period
        months_back = st.selectbox(
            "Time Period",
            options=[3, 6, 12],
            format_func=lambda x: f"Last {x} months",
            index=0
        )
        
        # Cache Invalidation Logic
        if 'last_months_back' not in st.session_state:
            st.session_state.last_months_back = months_back
        elif st.session_state.last_months_back != months_back:
            clear_analysis_cache()
            st.session_state.last_months_back = months_back
            st.toast("Time period changed. Analysis cache cleared.", icon="🔄")

        st.divider()
        
        # API Key Status
        ollama_api_key = get_secret("OLLAMA_API_KEY")
        st.subheader("🔑 Status")
        if ollama_api_key:
            st.success("✅ API Key Loaded")
            st.caption("Ready for Cloud Inference")
        else:
            st.warning("⚠️ No API Key Detected")
            st.caption("Local Ollama will be used (if available), or ensure OLLAMA_API_KEY is in secrets.toml")
            
        st.divider()
        st.info("Select a category tab to begin analysis.")

    # ------------------------------------------
    # Main Content: Tabs
    # ------------------------------------------
    categories = get_journals_by_category()
    
    # Create tabs
    tab_names = list(categories.keys())
    # Add an Overview tab? Or just categories. Let's stick to categories + Summary
    # The requirement was "Tabs based dynamically generated".
    
    tabs = st.tabs([f"📌 {name}" for name in tab_names])
    
    for i, (category, journals) in enumerate(categories.items()):
        with tabs[i]:
            st.header(f"{category} Analysis")
            
            col_left, col_right = st.columns([1, 2])
            
            with col_left:
                st.subheader("Select Journals")
                with st.container(border=True):
                    # Checkboxes for journals
                    selected_journals = []
                    
                    # "Select All" functionality within the form context is tricky with dynamic widgets,
                    # so we'll default all to Checked.
                    
                    for journal in journals:
                        # Use a unique key for each checkbox
                        if st.checkbox(f"**{journal['name']}**", value=True, key=f"chk_{category}_{journal['name']}"):
                            selected_journals.append(journal)
                    
                    if not selected_journals:
                        st.warning("Select at least one journal.")
                
                # Analyze Button
                analyze_btn = st.button(
                    f"🚀 Analyze {category} Trends", 
                    key=f"btn_analyze_{category}",
                    type="primary",
                    use_container_width=True,
                    disabled=(not selected_journals)
                )

            with col_right:
                result_key = f"result_{category}"
                papers_key = f"papers_{category}"
                
                if analyze_btn and selected_journals:
                    # Execute Analysis
                    collector = PaperCollector()
                    all_papers = []
                    
                    # 1. Fetch
                    with st.spinner(f"📡 Fetching papers from {len(selected_journals)} journals ({months_back} months)..."):
                        progress_bar = st.progress(0)
                        for idx, journal in enumerate(selected_journals):
                            fetched = collector.fetch_papers(journal["url"], months_back, max_papers=20)
                            for p in fetched:
                                p['source'] = journal['name']
                                all_papers.append(p)
                            progress_bar.progress((idx + 1) / len(selected_journals))
                        progress_bar.empty()
                    
                    if not all_papers:
                        st.error("No papers found in this period.")
                    else:
                        st.session_state[papers_key] = all_papers
                        
                        # 2. Analyze
                        with st.spinner("🧠 Asking Ollama Cloud to analyze trends..."):
                            try:
                                # Instantiate analyzer (API key handled internally by common_lib)
                                analyzer = TrendAnalyzer(model_name=model_name)
                                trend_text = analyzer.analyze_trends(all_papers, language=language)
                                st.session_state[result_key] = trend_text
                            except Exception as e:
                                st.error(f"Analysis failed: {str(e)}")

                # Display Results
                if result_key in st.session_state:
                    st.success(f"Analysis Complete! Based on {len(st.session_state.get(papers_key, []))} papers.")
                    
                    with st.container(border=True):
                        st.markdown("### 📊 AI Trend Report")
                        st.markdown(st.session_state[result_key])
                    
                    # Download Button
                    papers_data = st.session_state.get(papers_key, [])
                    html_report = generate_html_report(
                        category, 
                        st.session_state[result_key], 
                        papers_data
                    )
                    st.download_button(
                        label="📥 Download HTML Report",
                        data=html_report,
                        file_name=f"{category.lower().replace(' ', '_')}_report.html",
                        mime="text/html",
                        key=f"dl_{category}"
                    )
                        
                    # Show papers source list in expander
                    with st.expander("📚 View Source Papers"):
                        papers = st.session_state.get(papers_key, [])
                        for p in papers[:50]: # Limit display
                            st.markdown(f"- [{p['title']}]({p['link']}) ({p.get('published','')}) - *{p.get('source')}*")
                        if len(papers) > 50:
                            st.caption(f"...and {len(papers)-50} more.")
                
                elif not analyze_btn:
                    st.info("👈 Select journals and click Analyze to generate a report.")

if __name__ == "__main__":
    main()
